---
swagger: "2.0"
info:
  description: "This is customer microservice\n"
  version: "1.0.0"
  title: "Customer Product"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/joinet/customer/1.0.0"
tags:
- name: "account"
  description: "Account Register/Login"
- name: "admin"
  description: "Admin REST APIs"
- name: "customer"
  description: "Customer APIs"
- name: "invoice"
  description: "Customer order invoice and purchase item information"
schemes:
- "https"
- "http"
paths:
  /customer:
    post:
      tags:
      - "customer"
      summary: "Create new customer"
      operationId: "create_account"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Customer object that needs to be added to the customer table"
        required: true
        schema:
          $ref: "#/definitions/customer"
      responses:
        405:
          description: "Invalid input"
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
      x-swagger-router-controller: "swagger_server.controllers.customer_controller"
  /customer/{iCustomerId}/profile:
    get:
      tags:
      - "customer"
      summary: "Get customer profile information"
      operationId: "get_customer_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "iCustomerId"
        in: "path"
        description: "Customer Id needed to fetch all profile related information\
          \ of given customer"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/customer"
        400:
          description: "Invalid customer id provided"
        404:
          description: "Customer details not found"
      x-swagger-router-controller: "swagger_server.controllers.customer_controller"
    put:
      tags:
      - "customer"
      summary: "Updated user"
      description: "This can only be done by the logged in user."
      operationId: "update_customer"
      produces:
      - "application/json"
      parameters:
      - name: "iCustomerId"
        in: "path"
        description: "name that need to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated customer object"
        required: true
        schema:
          $ref: "#/definitions/customer"
      responses:
        400:
          description: "Invalid customer supplied"
        404:
          description: "User not found"
      x-swagger-router-controller: "swagger_server.controllers.customer_controller"
    delete:
      tags:
      - "customer"
      summary: "Delete user"
      description: "This can only be done by the logged in user."
      operationId: "delete_user"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "iCustomerId"
        in: "path"
        description: "The name that needs to be deleted"
        required: true
        type: "string"
      responses:
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
      x-swagger-router-controller: "swagger_server.controllers.customer_controller"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  customer_category:
    type: "object"
    properties:
      iCatId:
        type: "integer"
        format: "int64"
      vCategoryName:
        type: "string"
      dtCreated:
        type: "string"
        format: "date-time"
      dtUpdated:
        type: "string"
        format: "date-time"
    example:
      iCatId: 5
      dtCreated: "2000-01-23T04:56:07.000+00:00"
      dtUpdated: "2000-01-23T04:56:07.000+00:00"
      vCategoryName: "vCategoryName"
  customer_billing_address:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      vFlatNumber:
        type: "string"
      vAddressLine1:
        type: "string"
      vAddressLine2:
        type: "string"
      vLandMark:
        type: "string"
      vState:
        type: "string"
      vCity:
        type: "string"
      vPinCode:
        type: "string"
      dtCreated:
        type: "string"
        format: "date-time"
      dtUpdated:
        type: "string"
        format: "date-time"
    example:
      vAddressLine2: "vAddressLine2"
      dtCreated: "2000-01-23T04:56:07.000+00:00"
      vPinCode: "vPinCode"
      vLandMark: "vLandMark"
      vFlatNumber: "vFlatNumber"
      vState: "vState"
      dtUpdated: "2000-01-23T04:56:07.000+00:00"
      id: 6
      vAddressLine1: "vAddressLine1"
      vCity: "vCity"
  customer_shipping_address:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      vFlatNumber:
        type: "string"
      vAddressLine1:
        type: "string"
      vAddressLine2:
        type: "string"
      vLandMark:
        type: "string"
      vState:
        type: "string"
      vCity:
        type: "string"
      vPinCode:
        type: "string"
      dtCreated:
        type: "string"
        format: "date-time"
      dtUpdated:
        type: "string"
        format: "date-time"
    example:
      vAddressLine2: "vAddressLine2"
      dtCreated: "2000-01-23T04:56:07.000+00:00"
      vPinCode: "vPinCode"
      vLandMark: "vLandMark"
      vFlatNumber: "vFlatNumber"
      vState: "vState"
      dtUpdated: "2000-01-23T04:56:07.000+00:00"
      id: 1
      vAddressLine1: "vAddressLine1"
      vCity: "vCity"
  invoice_billing_address:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      vFlatNumber:
        type: "string"
      vAddressLine1:
        type: "string"
      vAddressLine2:
        type: "string"
      vLandMark:
        type: "string"
      vState:
        type: "string"
      vCity:
        type: "string"
      vPinCode:
        type: "string"
      dtCreated:
        type: "string"
        format: "date-time"
      dtUpdated:
        type: "string"
        format: "date-time"
  invoice_shipping_address:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      vFlatNumber:
        type: "string"
      vAddressLine1:
        type: "string"
      vAddressLine2:
        type: "string"
      vLandMark:
        type: "string"
      vState:
        type: "string"
      vCity:
        type: "string"
      vPinCode:
        type: "string"
      dtCreated:
        type: "string"
        format: "date-time"
      dtUpdated:
        type: "string"
        format: "date-time"
  invoice_tax:
    type: "object"
    properties:
      iTaxtId:
        type: "integer"
        format: "int32"
      vTaxName:
        type: "string"
      fTaxPercentage:
        type: "number"
        format: "double"
      eTaxType:
        type: "string"
        enum:
        - "Tax"
        - "Compound Tax"
      dtCreated:
        type: "string"
        format: "date-time"
      dtUpdated:
        type: "string"
        format: "date-time"
  invoice_product:
    type: "object"
    properties:
      iProductId:
        type: "integer"
        format: "int64"
      vProductName:
        type: "string"
      arrProductItem:
        type: "array"
        items:
          $ref: "#/definitions/invoice_product_item"
      eStatus:
        type: "string"
        enum:
        - "Active"
        - "InActive"
      dtCreated:
        type: "string"
        format: "date-time"
      dtUpdated:
        type: "string"
        format: "date-time"
  invoice_product_item:
    type: "object"
    properties:
      iProductItemId:
        type: "integer"
        format: "int64"
      vProductItemName:
        type: "string"
      vProductItemDescription:
        type: "string"
      fProductItemBasicAmount:
        type: "number"
        format: "double"
      fProductItemOfferAmount:
        type: "number"
        format: "double"
      oBillingCycle:
        $ref: "#/definitions/invoice_item_billing_cycle"
      bIsTaxable:
        type: "boolean"
      eProductItemType:
        type: "string"
        enum:
        - "Goods"
        - "Service"
      dtCreated:
        type: "string"
        format: "date-time"
      dtUpdated:
        type: "string"
        format: "date-time"
  invoice_item_billing_cycle:
    type: "object"
    properties:
      iCycleId:
        type: "integer"
        format: "int64"
      vCycleName:
        type: "string"
      iCycleDays:
        type: "integer"
        format: "int32"
      iCycleMonth:
        type: "integer"
        format: "int32"
  customer:
    type: "object"
    required:
    - "eGender"
    - "eTitle"
    - "iCAFNumer"
    - "vFirstName"
    - "vLastName"
    properties:
      iCustomerId:
        type: "integer"
        format: "int64"
      vFirstName:
        type: "string"
        example: "Sanjay"
      vLastName:
        type: "string"
        example: "Sinalkar"
      eGender:
        type: "string"
        example: "Male"
        description: "Customer gender information"
        enum:
        - "Male"
        - "Female"
      eTitle:
        type: "string"
        example: "Mr"
        description: "Customer title information"
        enum:
        - "Mr"
        - "Ms"
        - "Mrs"
        - "Miss"
      iCAFNumer:
        type: "integer"
        format: "int32"
        example: 12456
      vUsername:
        type: "string"
        example: "sanjay123"
        description: "Customer unique Username"
      vPassword:
        type: "string"
        description: "Customer encrypted password"
      vPasswordHash:
        type: "string"
        description: "Customer encrypted password  hash or salt"
      vGSTNumber:
        type: "string"
        example: "27AAJCS2264E2ZC"
        description: "Customer GST Number"
      vMobileNumber:
        type: "string"
        example: "911234554321"
        description: "Customer mobile Number"
      vEmail:
        type: "string"
        example: "test@example.com"
        description: "Customer email id"
      oBillingAddress:
        $ref: "#/definitions/customer_billing_address"
      oInstallationAddress:
        $ref: "#/definitions/customer_shipping_address"
      vCategory:
        $ref: "#/definitions/customer_category"
      dtCreated:
        type: "string"
        format: "date-time"
      dtUpdated:
        type: "string"
        format: "date-time"
      eStatus:
        type: "string"
        description: "Customer account status"
        enum:
        - "Active"
        - "Inactive"
        - "Suspended"
        - "Terminated"
    example:
      iCustomerId: 0
      vUsername: "sanjay123"
      vGSTNumber: "27AAJCS2264E2ZC"
      oBillingAddress:
        vAddressLine2: "vAddressLine2"
        dtCreated: "2000-01-23T04:56:07.000+00:00"
        vPinCode: "vPinCode"
        vLandMark: "vLandMark"
        vFlatNumber: "vFlatNumber"
        vState: "vState"
        dtUpdated: "2000-01-23T04:56:07.000+00:00"
        id: 6
        vAddressLine1: "vAddressLine1"
        vCity: "vCity"
      eGender: "Male"
      vPasswordHash: "vPasswordHash"
      dtUpdated: "2000-01-23T04:56:07.000+00:00"
      oInstallationAddress:
        vAddressLine2: "vAddressLine2"
        dtCreated: "2000-01-23T04:56:07.000+00:00"
        vPinCode: "vPinCode"
        vLandMark: "vLandMark"
        vFlatNumber: "vFlatNumber"
        vState: "vState"
        dtUpdated: "2000-01-23T04:56:07.000+00:00"
        id: 1
        vAddressLine1: "vAddressLine1"
        vCity: "vCity"
      vFirstName: "Sanjay"
      vLastName: "Sinalkar"
      dtCreated: "2000-01-23T04:56:07.000+00:00"
      eTitle: "Mr"
      vCategory:
        iCatId: 5
        dtCreated: "2000-01-23T04:56:07.000+00:00"
        dtUpdated: "2000-01-23T04:56:07.000+00:00"
        vCategoryName: "vCategoryName"
      vEmail: "test@example.com"
      iCAFNumer: 12456
      vPassword: "vPassword"
      vMobileNumber: "911234554321"
      eStatus: "Active"
  invoice:
    type: "object"
    properties:
      iInvoiceId:
        type: "integer"
        format: "int64"
      vInvoiceNumber:
        type: "string"
        example: "INV/2019-04-23/1256"
      vCustomerName:
        type: "string"
        example: "Sanjay Sinalkar"
      vCustomerGSTNumber:
        type: "string"
        example: "27AAJCS2264E2ZC"
      vBillingAddress:
        $ref: "#/definitions/invoice_billing_address"
      vInstallationAddress:
        $ref: "#/definitions/invoice_shipping_address"
      vCustomerCode:
        type: "string"
        example: "sanjay123"
      dtInvoiceDate:
        type: "string"
        format: "date"
        example: "2019-04-23"
      dtInvoiceDueDate:
        type: "string"
        format: "date"
        example: "2020-04-23"
      ePaymentMethod:
        type: "string"
        enum:
        - "Cash"
        - "Cheque"
        - "Online"
        - "Wallet"
        - "Swipe"
        - "NEFT"
      ePaymentStatus:
        type: "string"
        enum:
        - "Unpaid"
        - "Paid"
        - "Partial"
      vMobileNumber:
        type: "string"
        example: "911234554321"
      iSACCode:
        type: "integer"
        example: 9084220
      oProductItems:
        $ref: "#/definitions/invoice_product"
      oInvoiceBrand:
        $ref: "#/definitions/invoice_brand"
      vInvoicePeriod:
        type: "string"
        example: "23 April 2019 - 23 April 2020"
      fBasicAmount:
        type: "number"
        format: "double"
        example: 2999.0
      fDiscountAmount:
        type: "number"
        format: "double"
        example: 299.0
      fTotalAmountBeforeTax:
        type: "number"
        format: "double"
        example: 2699.0
      fTotalTaxAmount:
        type: "number"
        format: "double"
        example: 487.0
      fTotalAmount:
        type: "number"
        format: "double"
        example: 3186.0
      dtCreated:
        type: "string"
        format: "date-time"
      dtUpdated:
        type: "string"
        format: "date-time"
  invoice_brand:
    type: "object"
    properties:
      vBrandName:
        type: "string"
      vBrandLogo:
        type: "string"
      vBrandTaxInfo:
        type: "string"
      vBranContactInfo:
        type: "string"
      vBrandPaymentInfo:
        type: "string"
      vBrandOfficeAddress:
        type: "string"
      vBrandTerms:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
        example: 200
      type:
        type: "string"
      message:
        type: "string"
        example: "Successful"
    example:
      code: 200
      type: "type"
      message: "Successful"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
